### ISSUE TITLE
Error on `pactl list short sources`

### ISSUE THREAD

**Issue by sumanth-culli** [rom1v/aoa-audio#3]
Getting the following error after running `pactl list short sources`
```
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```
macOS mojave 10.14.4 
Any help? [This](https://github.com/Homebrew/homebrew-core/issues/9314#issuecomment-276341048) workaround doesn't work anymore.

**Comment by rom1v** [comment]
Sorry, I have no idea how it works on Mac OS.
