### ISSUE TITLE
several problems

### ISSUE THREAD

**Issue by ghost** [rom1v/aoa-audio#4]
1) Ive receive this output rather than running 

```
rockpi@rockpi:~/Desktop/aoa-audio$ pactl list short sources
0	alsa_output.platform-hdmi-sound.stereo-fallback.monitor	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
```

2) I cant access scrcpy while running this program. I have access without it running.
```
error: failed to get feature set: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
```

Thanks as always

**Comment by rom1v** [comment]
1. `SUSPENDED` is expected when no sound is played
2. Enabling AOA changes the USB pid of the device, and the new vid:pid is probably not authorized in your udev rules. Check the vid:pid with `lsusb`, and authorize it in `/etc/udev/rules.d/51-android.rules` or similar.
